### ISSUE TITLE
dodram intro

### ISSUE THREAD

**Issue by Melodiouss** [kingle1024/hb#1]
음식물 쓰레기를 자원화하는 세계적 선두 기업!

(주)도드람바이오를 방문해주신 여러분, 환영합니다.

(주)도드람바이오는 음식물 쓰레기를 사용하여 메탄가스 포집을 극대화하고 이를 전기로 자원화하여 국가 산업 발전에 기여하는 회사입니다.

세계 우수 기술들이 국내에서 성공을 거두지 못했던 가장 큰 이유는 음식문화 차이로 인한 국내 음식물 쓰레기 특성에 적합한 처리 공법을 갖추지 못하였기 때문입니다.

이 과정에서 도드람연구센터가 국가지원하에 2015년 세계 최고의 가스 포집을 통한 전기 발전 설비의 효율을 극대화한 시스템을 개발하였습니다.

공동 개발에 참여했던 함부르크 대학에서도 감탄과 칭찬을 아끼지 않은 쾌거였습니다.
이에 (주)도드람바이오는 축산분뇨에만 국한하지 않고 전처리공정에 신규처리 공법을 공유하여 음식물 쓰레기로 더 많은 양의 가스를 포집하는데 성공을 거두었습니다.

이러한 축적된 기술과 노하우를 바탕으로 상업용 소멸기 제작에서도 성공을 거두어 제품출시를 이루었고, 제품 규격화를 통한 신속한 A/S, 우수자재를 통한 최고의 설비를 만들어 내기 위해 설비 회사를 갖추었으며, 양질의 유기농 퇴비를 바라는 농가를 위해 반응기 공법을 도입하여 유기농 퇴비 생산 시스템도 구축하였습니다.

음식물 쓰레기, 축산분뇨, 기타오니 등의 모든 폐기물을 신규 공법으로 자원화하는 세계적인 친환경 그린 에너지 기업으로 자리매김 하고 있습니다.

저희 회사 임직원들은 여기에 만족하지 않고, ICT를 융합한 무인 시스템 개발에 박차를 가하고 있습니다.

여러분의 관심과 격려를 부탁 드립니다.

감사합니다.

(주)도드람바이오

**Comment by Melodiouss** [comment]
시박

**Comment by kingle1024** [comment]
처리완료
