### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Melodiouss** [kingle1024/hb#2]
1. 도드람 메인 대문사진 (카톡 첨부1)
- 가로로 긴 사진인데 들어가나? 
- 아니면 다른 방식으로 넣을 것인가

2. 헤브론 메인 대문사진 비율에 맞게 수정
- 만약 비율이 수정해도 이상하면 사진을 조금 작게 수정 (가운데 오도록)

3. 헤브론에도 제품및 견적문의 추가..

.
.

+ 헤브론 메인 가운데에 공지사항이 없어서 비어보여서
다른것도 (생산설비로 바로가기) 추가 (카톡 첨부2)

**Comment by kingle1024** [comment]
1. 도드람 메인 대문사진
![image](https://user-images.githubusercontent.com/25365672/49016324-1e11be80-f1c9-11e8-95e0-113ea110fee3.png)

**Comment by kingle1024** [comment]
3번 처리완료

**Comment by kingle1024** [comment]
@Melodiouss 
1번은 이미지 사이즈가 가로로 넓어 해당 사진을 넣기 위해서는 레이아웃을 재배열 해야 할 것 같습니다. 
혹은 기존처럼 세로로 긴 사진이 있으면 대체 부탁드립니다.
2번 헤브론 공지사항에 무슨 그림 혹은 글을 넣어야 하나요?

**Comment by kingle1024** [comment]
1 -> 재선님이 하기로함
2 -> 재선님이 하기로함
이슈 종료하겠습니다
